modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "tinyallies"
version = "${version}"
displayName = "Tiny Allies"
authors = "Lgowz"
description = '''
Tiny Allies adds tamable baby versions of the classic vanilla monsters!
'''
#logoFile = "assets/tinyallies/icon.png"

[[dependencies.tinyallies]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinyallies]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinyallies]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"